---
jaeger:
  enabled: true
  # default to all-in-one
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    ingress:
      enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector"
  enabled: true
  nameOverride: otelcol
  command:
    name: "otelcol"
  mode: deployment
  presets:
    kubernetesAttributes:
      enabled: true
  service:
    type: ClusterIP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: "{{ .Release.Name }}-jaeger-collector:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          exporters: [otlp, debug]
          processors: [batch]
          receivers: [otlp]
