---
jaeger:
  enabled: true
  # default to all-in-one
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    ingress:
      enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false