---
jaeger:
  enabled: true
  # default to all-in-one
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
    ingress:
      enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector-contrib"
  enabled: true
  nameOverride: otelcol
  mode: deployment
  presets:
    kubernetesAttributes:
      enabled: true
  service:
    type: ClusterIP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      otlp:
        endpoint: "{{ .Release.Name }}-jaeger-collector:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          exporters: [otlp, debug]
          processors: [batch]
          receivers: [otlp]
