apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
spec:
  defaultBackend:
    service:
      name: otel-actix-service
      port:
        number: 80
