services:
  collector:
    image: ghcr.io/os-observability/redhat-opentelemetry-collector/redhat-opentelemetry-collector:v0.119.0
    command: ["--config=/otel-collector-config.yaml"]
    volumes:
      - './otel-collector-config.yaml:/otel-collector-config.yaml:z'
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9464:9464"
