
name: aaaaa 

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.0
      - run: |
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
